imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig', 'php'] }     #assets_version: SomeVersionScheme
    default_locale: %locale%
    session:
        name:           ratp

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
   
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

services:
   baquaras.appli.admin.appliuser:
      class: Baquaras\AppliBundle\Admin\AppliUserAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Tables, label: AppliUser }
      arguments: [null, Baquaras\AppliBundle\Entity\AppliUser, SonataAdminBundle:CRUD]

   baquaras.appli.admin.role:
      class: Baquaras\AppliBundle\Admin\RoleAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Tables, label: Role }
      arguments: [null, Baquaras\AppliBundle\Entity\Role, SonataAdminBundle:CRUD]

   baquaras.appli.admin.agent:
      class: Baquaras\AppliBundle\Admin\AgentAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Tables, label: Agent }
      arguments: [null, Baquaras\AppliBundle\Entity\Agent, SonataAdminBundle:CRUD]

sonata_admin:
    templates:
        # default global templates
        layout:  BaquarasAppliBundle:Admin:standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                mapping_types:
                    enum: string
                    point: string
            siera:
                driver:   "%database_driver_siera%"
                host:     "%database_host_siera%"
                port:     "%database_port_siera%"
                dbname:   "%database_name_siera%"
                user:     "%database_user_siera%"
                password: "%database_password_siera%"
                charset:  UTF8
                
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
       # metadata_cache_driver: apc
        #result_cache_driver: apc
        #query_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

be_simple_sso_auth:
    websso:
        protocol:
            id: cas
            version: 2
        server:
            id: cas
            login_url: https://t-sahara.info.ratp/websso/login
            logout_url: https://t-sahara.info.ratp/websso/logout
            validation_url: https://t-sahara.info.ratp/websso/serviceValidate
