security:
    encoders:
        Baquaras\TestBundle\Security\User: plaintext

    role_hierarchy:
        ROLE_INTEGRATEUR: ROLE_INTEGRATEUR
        ROLE_ADMIN: [ROLE_USER, ROLE_LECTEUR, ROLE_TECHNICIEN, ROLE_QUALIFICATEUR, ROLE_CHEF_PRODUIT,ROLE_RESPONSABLE_QUALIF ]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        main:
            id: user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        my_firewall:
            pattern:    ^/.*$
            security: true
            provider : main 
            anonymous: ~
            logout:     true
            trusted_sso:
                manager: websso
                login_action: false
                logout_action: false
                login_path: /secured/login
                check_path: /login_check
                #default_target_path: /accueil
                #failure_path: /accueil
                #failure_forward: true
            logout:
                path:   /logout
                target: /
            
                


    access_control:
        - { path: ^/accueil, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/secured/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
       # - { path: ^/*, roles: ROLE_INTEGRATEUR }