security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        main:
            entity: { class: Baquaras\TestBundle\Entity\Utilisateur, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        my_firewall:
            pattern:    ^/.*$
            security: true
            switch_user: true
            provider : main
            logout:       true
            anonymous:    true
            trusted_sso:
                manager: websso
                login_action: false
                logout_action: false #BeSimpleSsoAuthBundle:TrustedSso:logout
                login_path: /secured/login
                check_path: /login_check
                create_users: false
                default_target_path: accueil
            logout:
                invalidate_session: true
                path:   /logout
                target: /acceuil

    access_control:
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/accueil, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/secured/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/secured/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/*, roles: ROLE_ADMIN }

