parameters:
    user_provider.class: Baquaras\TestBundle\Security\User\UtilisateurRepository
    management_roles.class: Baquaras\TestBundle\Services\ManagementRoles
    authorisation_extension.class: Baquaras\TestBundle\Twig\AuthorisationExtension
    baquaras.security.logout_success_handler.class: Baquaras\TestBundle\Services\LogoutSuccess
    baquaras.connect_siera.class: Baquaras\TestBundle\Services\ConnectSiera

services:
    user_provider:
        class: "%user_provider.class%"
        factory_service: doctrine.orm.default_entity_manager 
        factory_method: getRepository 
        arguments: ['BaquarasTestBundle:Utilisateur']

    management_roles:
        class: "%management_roles.class%"
        calls:
            - [ setContainer, [ @service_container ] ]
    
    authorisation_extension:
        class: "%authorisation_extension.class%"
        calls:
            - [ setManagementRoles, [ @management_roles ] ]
        tags:
            -  { name: twig.extension }
            
    baquaras.security.logout_success_handler:
        class: "%baquaras.security.logout_success_handler.class%"
    
    baquaras.connect_siera:
        class: "%baquaras.connect_siera.class%"
        arguments: ['@service_container']
    
    baquaras.form.type.application_ajout:
        class: Baquaras\TestBundle\Form\ApplicationAjoutType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: baquaras_testbundle_application }