parameters:
    user_provider.class: Baquaras\TestBundle\Security\User\UtilisateurRepository
    management_roles.class: Baquaras\TestBundle\Services\ManagementRoles

services:
    user_provider:
        class: "%user_provider.class%"
        factory_service: doctrine.orm.default_entity_manager 
        factory_method: getRepository 
        arguments: ['BaquarasTestBundle:Utilisateur']

    management_roles:
        class: "%management_roles.class%"
        factory_service: doctrine.orm.default_entity_manager