<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Bundle\\MonologBundle\\' => array($vendorDir . '/symfony/monolog-bundle'),
    'Symfony\\Bundle\\AsseticBundle\\' => array($vendorDir . '/symfony/assetic-bundle'),
    'Sonata\\DoctrineORMAdminBundle\\' => array($vendorDir . '/sonata-project/doctrine-orm-admin-bundle'),
    'Sonata\\CoreBundle\\' => array($vendorDir . '/sonata-project/core-bundle'),
    'Sonata\\Cache\\Tests\\' => array($vendorDir . '/sonata-project/cache/test'),
    'Sonata\\Cache\\' => array($vendorDir . '/sonata-project/cache/lib'),
    'Sonata\\CacheBundle\\' => array($vendorDir . '/sonata-project/cache-bundle'),
    'Sonata\\BlockBundle\\' => array($vendorDir . '/sonata-project/block-bundle'),
    'Sonata\\AdminBundle\\' => array($vendorDir . '/sonata-project/admin-bundle'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Cocur\\Slugify\\' => array($vendorDir . '/cocur/slugify/src'),
);
