<?php

namespace Baquaras\AppliBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentRepository extends EntityRepository
{
    /**
     * Retourne les agent crée de date1 à date2 (Agent.created_at)
     * @param \Datetime $date1
     * @param \Datetime $date2
     */
    public function getByDateCreatedAt(\Datetime $date1, \Datetime $date2)
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->where('a.created_at BETWEEN :date1 AND :date2')
        ->setParameter('date1', $date1->format('Y-m-d'))
        ->setParameter('date2', $date2->format('Y-m-d'));

        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }
}