imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig', 'php'] }     #assets_version: SomeVersionScheme
    default_locale: %locale%
    session:
        name:           ratp

    #router:
    #    resource: "%kernel.root_dir%/config/routing.yml"
    #    strict_requirements: ~
    #form:            ~
    #csrf_protection: ~
    #validation:      { enable_annotations: true }
    #templating:
     #   engines: ['twig']
        #assets_version: SomeVersionScheme
    #default_locale:  "%locale%"
    #trusted_hosts:   ~
    #trusted_proxies: ~
    #session:
        # handler_id set to null will use default session handler from php.ini
    #    handler_id:  ~
    #fragments:       ~
    #http_method_override: true
    serializer:
        enabled: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    assets:
        jquery_js:
            inputs:
            - "%kernel.root_dir%/Resources/public/js/jquery.min.js"
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [ ]
    #java: /usr/bin/java
   
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

services:
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
         - { name: serializer.normalizer }

    baquaras.appli.admin.appliuser:
        class: Baquaras\AppliBundle\Admin\AppliUserAdmin
        tags:
         - { name: sonata.admin, manager_type: orm, group: Tables, label: AppliUser }
        arguments: [null, Baquaras\AppliBundle\Entity\AppliUser, SonataAdminBundle:CRUD]

    baquaras.appli.admin.role:
        class: Baquaras\AppliBundle\Admin\RoleAdmin
        tags:
         - { name: sonata.admin, manager_type: orm, group: Tables, label: Role }
        arguments: [null, Baquaras\AppliBundle\Entity\Role, SonataAdminBundle:CRUD]

    baquaras.appli.admin.agent:
        class: Baquaras\AppliBundle\Admin\AgentAdmin
        tags:
         - { name: sonata.admin, manager_type: orm, group: Tables, label: Agent }
        arguments: [null, Baquaras\AppliBundle\Entity\Agent, SonataAdminBundle:CRUD]

sonata_admin:
    templates:
        # default global templates
        layout:  BaquarasAppliBundle:Admin:standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:
# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
            point: string
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

be_simple_sso_auth:
    websso:
        protocol:
            id: cas
            version: 2
        server:
            id: cas
            #login_url: %sso_login_url%
            #logout_url: %sso_logout_url%