security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Baquaras\AppliBundle\Entity\AppliUser, property: username }
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
       # main:
       #     form_login:
       #         login_path: /login
       #         use_forward: false
       #         check_path: /login_check
       #         post_only: true 
       #         default_target_path: /accueil
       #         username_parameter: _username
       #         password_parameter: _password
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"


        my_firewall:
            pattern: ^/.*$
            anonymous: ~
            logout:
                path:   /secured/logout
                target: /
            trusted_sso:
                manager: websso
                login_action: false
                logout_action: false
                login_path: /secured/login
                check_path: /accueil
                always_use_default_target_path : true
                default_target_path : /accueil
                #failure_path: /secured/logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }