<?php

namespace Baquaras\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
	public function getItems($liste)
	{
		$qb = $this->getItemsQueryBuilder($liste);
		return $qb->getQuery()->getResult();
	}

	public function getItemsQueryBuilder($liste)
	{
		return $this->createQueryBuilder('i')
			->select('i')
			->where('i.liste = :liste')
			->setParameter('liste', $liste);
	}
}
