<?php

namespace Baquaras\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModeOperatoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeOperatoireRepository extends EntityRepository
{
}
