<?php

namespace Baquaras\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OSCibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OSCIbleRepository extends EntityRepository
{
}