<?php

namespace Baquaras\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutRepository extends EntityRepository {

    /*
     * Get not suspend stats
     */
    public function getStatNotSuspends() 
    {
        $query = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('s')
                ->from('BaquarasTestBundle:Statut', 's')
                ->where('s.libelle NOT LIKE :statut')
                ->setParameter('statut', '%suspendue%');
        $stats = $query->getQuery()->getResult();
        
        return $stats;
    }

}
