<?php

namespace Baquaras\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    /**
     *
     * @return array(Utilisateur)
     */
     public function findUser() {
         return $this->getEntityManager()
         ->createQuery( 'SELECT u FROM BaquarasTestBundle:Utilisateur u  WHERE  u.nom LIKE :term')
         ->getResult();
}
}
